version: '3'
services:
  arango:
    container_name: arango
    image: arangodb
    ports:
      - '8529:8529'
    environment:
      - ARANGO_NO_AUTH=1
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '4000:4000'
    links:
      - arango
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - '3000:3000'
    links:
      - api
